# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eamic02

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://eamic.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fccd71d7b9524c34b5ff91ec4e7b6a26 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7f76d1acc079436eacc303ee0b2ce78e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: eamic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fccd71d7b9524c34b5ff91ec4e7b6a26 }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eamic02'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b8624035a4584dce8027634d07edaa00 }}
        images: 'eamic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fccd71d7b9524c34b5ff91ec4e7b6a26 }}/nginx:${{ github.sha }}'